<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Miller Liao">
<meta name="dcterms.date" content="2026-08-26">
<meta name="description" content="Lichess publishes millions of rated games each month, but engine evaluations appear only when a user requests analysis — in November 2017, just 7.5% of games had them. This project asks whether that convenient subset represents the full population, and how much adjustment can reduce the difference.">

<title>Which Chess Games Get Engine Analysis? – Miller Liao</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-5f0e52f7877e3a078c44e13fc828ca0d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-11a0e1da962a2b0ba0ef0836a8805e9c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Sora:wght@600;700&amp;family=Figtree:wght@400;600&amp;family=IBM+Plex+Mono:wght@400&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Miller Liao</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#a-useful-subset-but-not-a-random-one" id="toc-a-useful-subset-but-not-a-random-one" class="nav-link active" data-scroll-target="#a-useful-subset-but-not-a-random-one">1. A useful subset — but not a random one</a></li>
  <li><a href="#slower-games-are-analyzed-far-more-often" id="toc-slower-games-are-analyzed-far-more-often" class="nav-link" data-scroll-target="#slower-games-are-analyzed-far-more-often">2. Slower games are analyzed far more often</a></li>
  <li><a href="#why-are-evaluated-games-lower-rated" id="toc-why-are-evaluated-games-lower-rated" class="nav-link" data-scroll-target="#why-are-evaluated-games-lower-rated">3. Why are evaluated games lower-rated?</a></li>
  <li><a href="#a-small-difference-in-average-game-length-hides-a-much-stronger-pattern" id="toc-a-small-difference-in-average-game-length-hides-a-much-stronger-pattern" class="nav-link" data-scroll-target="#a-small-difference-in-average-game-length-hides-a-much-stronger-pattern">4. A small difference in average game length hides a much stronger pattern</a></li>
  <li><a href="#can-weighting-repair-the-evaluated-subset" id="toc-can-weighting-repair-the-evaluated-subset" class="nav-link" data-scroll-target="#can-weighting-repair-the-evaluated-subset">5. Can weighting repair the evaluated subset?</a></li>
  <li><a href="#analysis-clusters-around-players" id="toc-analysis-clusters-around-players" class="nav-link" data-scroll-target="#analysis-clusters-around-players">6. Analysis clusters around players</a></li>
  <li><a href="#bias-depends-on-what-you-measure" id="toc-bias-depends-on-what-you-measure" class="nav-link" data-scroll-target="#bias-depends-on-what-you-measure">7. Bias depends on what you measure</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">8. Limitations</a></li>
  <li><a href="#conclusion-selection-is-about-both-games-and-players" id="toc-conclusion-selection-is-about-both-games-and-players" class="nav-link" data-scroll-target="#conclusion-selection-is-about-both-games-and-players">9. Conclusion: selection is about both games and players</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix">Appendix</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Which Chess Games Get Engine Analysis?</h1>
<p class="subtitle lead">A selection-bias audit of 14.3 million Lichess games</p>
  <div class="quarto-categories">
    <div class="quarto-category">Selection Bias</div>
    <div class="quarto-category">Inverse Probability Weighting</div>
    <div class="quarto-category">Clustered Data</div>
    <div class="quarto-category">Online Chess</div>
  </div>
  </div>

<div>
  <div class="description">
    Lichess publishes millions of rated games each month, but engine evaluations appear only when a user requests analysis — in November 2017, just 7.5% of games had them. This project asks whether that convenient subset represents the full population, and how much adjustment can reduce the difference.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Miller Liao </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Lichess publishes complete monthly records of its rated games, while engine evaluations are available only for games that users chose to analyze. Some research uses these pre-existing evaluations rather than rerunning an engine over millions of games, which raises a basic sampling question: do evaluated games represent the full population? I examine all 14,306,375 standard rated games from November 2017, of which 7.54% contained engine evaluations.</p>
    <p>The evaluated subset differs systematically from the population. Classical games, the slowest live time control, are represented 3.3 times as heavily as in the full dataset, while evaluated games average 41 rating points lower. These marginal differences understate the structure underneath them. Within fast time controls, higher-rated games are less likely to be analyzed; within slow time controls, the relationship reverses. Game length is also strongly non-linear: analysis rates vary sixteen-fold across game-length categories, even though the average lengths of evaluated and unevaluated games differ by only a few plies.</p>
    <p>Observable differences can be reduced, but not eliminated, by adjustment. On prespecified holdout variables — recorded variables chosen in advance and deliberately excluded from the weighting model — inverse-probability weighting removes 29–47% of the original discrepancy. Selection is also strongly associated with players themselves: adding each player’s history of requesting analysis raises in-sample AUC from 0.664 to 0.827. Because move-quality outcomes are unavailable for unevaluated games, this design cannot directly measure bias in those outcomes. It does show, however, that pre-existing Lichess evaluations form a user-selected, player-clustered sample whose observable discrepancies are only partly repaired by game-level adjustment.</p>
  </div>
</div>


</header>


<p><em>Data: Lichess open database, November 2017. Methods, diagnostics, and code availability: <a href="#appendix">the appendix</a>.</em></p>
<section id="a-useful-subset-but-not-a-random-one" class="level2">
<h2 class="anchored" data-anchor-id="a-useful-subset-but-not-a-random-one">1. A useful subset — but not a random one</h2>
<p>Lichess publishes millions of rated games each month. Some also contain engine evaluations: a score after each move indicating which side the computer thinks is ahead, and by roughly how much. These annotations are convenient for research that needs engine-based measures, because generating comparable evaluations for millions of positions requires substantial computation.</p>
<p>But the evaluations are not assigned at random. In November 2017, only 1,078,379 of 14,306,375 standard rated games (7.54%) contained them.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> A game receives an evaluation only when someone requests analysis,<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> so the evaluated subset reflects users’ choices about which games are worth examining.</p>
<div id="fig-hero" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hero-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/fig_hero_headline.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="FIG.&nbsp;1&nbsp;— Only 7.54% of standard rated Lichess games in November 2017 carried pre-existing engine evaluations. Because those evaluations appear only after someone requests analysis, this is a small, user-selected subset rather than a random slice of the month."><img src="images/fig_hero_headline.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hero-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;1&nbsp;— Only 7.54% of standard rated Lichess games in November 2017 carried pre-existing engine evaluations. Because those evaluations appear only after someone requests analysis, this is a small, user-selected subset rather than a random slice of the month.
</figcaption>
</figure>
</div>
<p>What makes this selection problem unusually tractable is that the other 92.46% of games have not disappeared. Their time controls, ratings, lengths, terminations, and results remain in the same database. I can therefore compare the evaluated subset directly with the full population on these observed characteristics, rather than having to infer what the unselected cases might have looked like.</p>
<p>That comparison has an important limit. Engine-derived, move-level outcomes such as blunder rates are unavailable for unevaluated games, so this study cannot directly measure bias in those outcomes. The question here is narrower: how does the evaluated subset differ on characteristics that are observable for every game, and how much of those differences can statistical adjustment reduce?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Does this apply to your study?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It depends on how the engine evaluations are obtained.</p>
<p>If researchers choose their games first and then run an engine on every selected game, user analysis requests do not determine which games receive evaluations. <span class="citation" data-cites="cuvitoglu2026">Cüvitoğlu (<a href="#ref-cuvitoglu2026" role="doc-biblioref">2026</a>)</span> and <span class="citation" data-cites="elbert2026">Elbert et al. (<a href="#ref-elbert2026" role="doc-biblioref">2026</a>)</span>, for example, use this approach. It avoids the selection mechanism studied here, at the cost of running the engine themselves over millions of games.</p>
<p>If researchers instead use evaluations already stored in the Lichess data, they avoid that computational cost but inherit the subset that users chose to analyze. <span class="citation" data-cites="mcilroyyoung2020">McIlroy-Young et al. (<a href="#ref-mcilroyyoung2020" role="doc-biblioref">2020</a>)</span>, for example, restricted their study to the roughly 10% of games that already carried Stockfish evaluations. This article studies the selection problem created by that second approach.</p>
</div>
</div>
</div>
</section>
<section id="slower-games-are-analyzed-far-more-often" class="level2">
<h2 class="anchored" data-anchor-id="slower-games-are-analyzed-far-more-often">2. Slower games are analyzed far more often</h2>
<p>Before looking at the data, take a guess: which of 14.3 million games do people choose to analyze — the ones that took a long time to play, the ones between stronger players, or the ones that ran many moves? The next three sections test those three guesses in turn.</p>
<p>Let us begin with time control. At each speed, what share of games carries an evaluation?</p>
<div id="fig-controls" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-controls-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/fig1_rates_by_control.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="FIG.&nbsp;2&nbsp;— Slow time controls are disproportionately likely to be analyzed. Panel (a) shows each control’s share of all games in November; panel (b) shows the fraction of games within each control that carry an engine evaluation. Classical accounts for only 1.7% of the month but has a 25.0% analysis rate, while the much more common fast controls are analyzed far less often. Whiskers show 95% player-resampling stability intervals; exact values appear in Table&nbsp;5."><img src="images/fig1_rates_by_control.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-controls-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;2&nbsp;— Slow time controls are disproportionately likely to be analyzed. Panel (a) shows each control’s share of all games in November; panel (b) shows the fraction of games within each control that carry an engine evaluation. Classical accounts for only 1.7% of the month but has a 25.0% analysis rate, while the much more common fast controls are analyzed far less often. Whiskers show 95% player-resampling stability intervals; exact values appear in <a href="#tbl-c1" class="quarto-xref">Table&nbsp;5</a>.
</figcaption>
</figure>
</div>
<p>A Classical game is 5.9 times as likely to be analyzed as an UltraBullet game. The first guess is right: a game you spent half an hour playing feels worth revisiting; a thirty-second game often does not.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>If the evaluated subset were treated as representative, Classical chess would appear to make up 5.6% of Lichess games. Its actual share of the full month is only 1.7% (a 3.3x overrepresentation). The subset also underrepresents tournament games (11.3% versus 16.5%) and games involving highly active players: the two players’ average monthly game count is 368 in evaluated games, compared with 508 overall.</p>
<p>Time control gives a clear first answer: slower games are overrepresented. Rating is more complicated, because its pattern changes with time control.</p>
</section>
<section id="why-are-evaluated-games-lower-rated" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="why-are-evaluated-games-lower-rated">3. Why are evaluated games lower-rated?</h2>
<p>A natural guess is that stronger players review their games more often. It was also one of my prespecified expectations: evaluated games should have higher ratings.</p>
<p>They do not. Evaluated games average a <strong>game rating</strong><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> of 1580, compared with a higher average of 1621 across all games in the full month. That is a 41-point gap in the opposite direction from the one I expected.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>The pooled curve in <a href="#fig-rating-curve" class="quarto-xref">Figure&nbsp;3</a> points in the same direction. Except above 2400, games become less likely to carry an evaluation as rating rises. Why would stronger players appear less likely to analyze their games?</p>
<div id="fig-rating-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rating-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/fig2_marginal_rating.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="FIG.&nbsp;3&nbsp;— Pooling all time controls produces a U-shaped relationship between rating and analysis: the rate falls from 10.9% below 1000 to 6.2% at 1800–2000, then rises to 11.3% above 2400. This is a marginal pattern, and it does not show whether the same relationship holds within each time control. Game rating is the mean of the two players’ pre-game ratings; intervals are 95% Wilson intervals, and sparse bins are omitted."><img src="images/fig2_marginal_rating.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rating-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;3&nbsp;— Pooling all time controls produces a U-shaped relationship between rating and analysis: the rate falls from 10.9% below 1000 to 6.2% at 1800–2000, then rises to 11.3% above 2400. This is a marginal pattern, and it does not show whether the same relationship holds within each time control. Game rating is the mean of the two players’ pre-game ratings; intervals are 95% Wilson intervals, and sparse bins are omitted.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why are some rating bins omitted?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Not every percentage is based on the same amount of data, and a percentage carries little information when the bin behind it is too small. In an early version of this figure, the 700-rating bin contained only four games in total. One happened to have an evaluation, which produced an apparently striking 25% analysis rate.</p>
<p>Its 95% Wilson interval ran from 4% to 71%, revealing that the apparent spike told us almost nothing. By contrast, bins containing tens of thousands of games have much tighter intervals.</p>
<p>I therefore show Wilson intervals to make this difference in precision visible, and omit bins too sparse to interpret. Wilson intervals suit this job because they stay between 0% and 100% and behave well when counts are small or proportions sit near the extremes.</p>
</div>
</div>
</div>
<p>The initial expectation might simply have been wrong. Before drawing that conclusion, however, the pooled result needed to be taken apart. Section 2 showed that analysis rates differ sharply by time control. The mix of time controls also changes with rating: below 1000, more than a quarter of games are Rapid or Classical; above 2400, 96% are Bullet or Blitz.</p>
<p>At any rating, the pooled analysis rate is an average of the rates in the six time controls, weighted by how many games each control contributes. Because those weights change across rating bands, the pooled curve combines two sources of variation: analysis behavior may change within a time control, or the mixture of time controls may change. It cannot tell us how much comes from each.</p>
<p>The same mixture can affect the 41-point difference in average rating. I separated the gap with a <strong>Kitagawa decomposition</strong><a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>. The decomposition splits the 41-point gap into two pieces: how much comes from the evaluated subset containing a different mix of time controls, and how much remains when evaluated and unevaluated games are compared within the same time controls.</p>
<div id="tbl-kitagawa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-kitagawa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;1&nbsp;— Kitagawa decomposition of the 41-point rating gap. Differences in the mix of time controls account for 24.2% of the gap; 75.8% remains within time controls.
</figcaption>
<div aria-describedby="tbl-kitagawa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source of the rating gap</th>
<th style="text-align: right;">Contribution</th>
<th style="text-align: right;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Different mix of time controls</td>
<td style="text-align: right;">−9.9 points</td>
<td style="text-align: right;">24.2%</td>
</tr>
<tr class="even">
<td>Rating differences within time controls</td>
<td style="text-align: right;">−31.0 points</td>
<td style="text-align: right;">75.8%</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>−40.9 points</strong></td>
<td style="text-align: right;"><strong>100%</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Only 24.2% of it (<strong>stability interval</strong><a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> 22.6–25.8%) comes from the mixture of time controls. This part is easy to explain. Lichess maintains a separate rating pool for each time control, and their numerical centers differ: the median game rating is 1733 in UltraBullet but 1455 in Classical. Classical has both the highest analysis rate and the lowest median rating, so its overrepresentation pulls down the evaluated subset’s average. The mechanism is real, but it explains only one quarter of the gap.</p>
<p>The remaining 31 points arise within time controls. In other words, the lower average rating is not mainly an artifact of combining differently centered rating pools. The relationship between rating and analysis itself changes direction across time controls, as <a href="#fig-interaction" class="quarto-xref">Figure&nbsp;4</a> shows.</p>
<div id="fig-interaction" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<a href="images/fig3_interaction.png" class="lightbox page-columns page-full" data-gallery="quarto-lightbox-gallery-4" title="FIG.&nbsp;4&nbsp;— The relationship between rating and analysis reverses with time control. (a) Analysis rates generally fall with rating in UltraBullet, Bullet, and Blitz — apart from a small group of very highly rated games — but rise in Rapid, Classical, and Correspondence. (b) The comparison between 2000–2200 and 1200–1400 makes the pattern explicit: ratios below 1 mean higher-rated games are analyzed less often, ratios above 1 mean they are analyzed more often, and the reversal falls between Blitz and Rapid. Whiskers show 95% player-resampling stability intervals (B = 200); exact ratios appear in Table&nbsp;6."><img src="images/fig3_interaction.png" class="img-fluid figure-img column-page-inset"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;4&nbsp;— The relationship between rating and analysis reverses with time control. (a) Analysis rates generally fall with rating in UltraBullet, Bullet, and Blitz — apart from a small group of very highly rated games — but rise in Rapid, Classical, and Correspondence. (b) The comparison between 2000–2200 and 1200–1400 makes the pattern explicit: ratios below 1 mean higher-rated games are analyzed less often, ratios above 1 mean they are analyzed more often, and the reversal falls between Blitz and Rapid. Whiskers show 95% player-resampling stability intervals (B = 200); exact ratios appear in <a href="#tbl-c2" class="quarto-xref">Table&nbsp;6</a>.
</figcaption>
</figure>
</div>
<p>Within UltraBullet, Bullet, and Blitz, higher-rated games are analyzed less often. An UltraBullet game rated 2000–2200, for example, is analyzed only 0.26 times as often as one rated 1200–1400. Within Rapid, Classical, and Correspondence, the direction reverses. Analysis rates are relatively similar across time controls at lower ratings, but split sharply as rating rises: they fall in fast chess and rise in slow chess.</p>
<p>One possible interpretation is that fast and slow chess encourage different reviewing habits. The data establishes the divergence, but not why it occurs.</p>
<p>Because Bullet and Blitz make up 76% of all games, their downward rating gradients dominate the pooled results. Once the time controls are separated, both the lower average rating and the U-shaped pooled curve become understandable: they combine relationships pointing in opposite directions, with weights that change across rating bands. The pooled curve is numerically correct, but it does not describe a single rating pattern shared by all games.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why can’t we report one “effect of rating”?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the relationship depends on time control. In fast chess, higher rating goes with less analysis; in slow chess, it goes with more. A single rating coefficient would average relationships with opposite signs and describe neither one well.</p>
<p>The selection model must therefore include a rating × time-control interaction, and the reweighting must balance their joint categories rather than treating rating and time control separately. I also refer to a selection-rate gradient or association, not a causal “effect”: these data do not identify one.</p>
</div>
</div>
</div>
</section>
<section id="a-small-difference-in-average-game-length-hides-a-much-stronger-pattern" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="a-small-difference-in-average-game-length-hides-a-much-stronger-pattern">4. A small difference in average game length hides a much stronger pattern</h2>
<p>Game length initially looked like the least interesting variable in the dataset. A ply is one move by one player, so two plies, back and forth, make one full move. Evaluated games averaged 64.2 plies; unevaluated games averaged 67.7. That 3.5-ply difference looked modest enough that during my first pass of the dataset, I recorded it as “no significant effect.”</p>
<p>Then I stopped comparing only the averages. I divided games into seven length groups and calculated the evaluation rate within each one.</p>
<div id="fig-length" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<a href="images/fig4_length.png" class="lightbox page-columns page-full" data-gallery="quarto-lightbox-gallery-5" title="FIG.&nbsp;5&nbsp;— Analysis is most common for games of intermediate length, producing a hump rather than a steady increase or decrease. Panel (a) shows the overall pattern: the rate rises from 0.65% for games of ten plies or fewer to 10.4% at 41–60 plies, then declines. Panel (b) shows the same 41–60-ply peak within all six time controls, so the hump is not a by-product of differences in time-control composition. Rates are calculated among all games in each length group; the shaded band marks 41–60 plies. Exact values appear in Table&nbsp;7."><img src="images/fig4_length.png" class="img-fluid figure-img column-page-inset"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;5&nbsp;— Analysis is most common for games of intermediate length, producing a hump rather than a steady increase or decrease. Panel (a) shows the overall pattern: the rate rises from 0.65% for games of ten plies or fewer to 10.4% at 41–60 plies, then declines. Panel (b) shows the same 41–60-ply peak within all six time controls, so the hump is not a by-product of differences in time-control composition. Rates are calculated among all games in each length group; the shaded band marks 41–60 plies. Exact values appear in <a href="#tbl-c3" class="quarto-xref">Table&nbsp;7</a>.
</figcaption>
</figure>
</div>
<p>The pattern is a hump, not a steady increase or decrease. Across the full month, the evaluation rate spans a factor of 16 between the shortest group and the peak. A low rate among very short games was unsurprising. The decline among very long games was not. Evaluations are most common for games lasting 41–60 plies (20–30 full moves) and become less common toward either tail.</p>
<p>The same hump appears within every time control, with all six peaking in the 41–60-ply range. So the pattern is not simply a consequence of slower and faster games having different typical lengths.</p>
<p>Why, then, do the average lengths differ by only 3.5 plies? Because unevaluated games are more common at both extremes. Games lasting 10 plies or fewer make up 1.55% of the unevaluated group but only 0.124% of the evaluated group (a 12.5-fold difference). At the other end, games longer than 120 plies account for 6.2% of unevaluated games and 3.9% of evaluated games. The excess of very short games pulls the mean down, while the excess of very long games pulls it up. The two effects partly cancel, leaving a small difference in the averages even though the underlying distributions differ substantially.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How different are the full length distributions?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The 3.5-ply difference in means summarizes two distributions with a single number, which lets differences in opposite tails partly cancel. A distributional comparison asks something else: how far apart are the two distributions across the whole range of game lengths?</p>
<div id="fig-ecdf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ecdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/fig4_why_distributions.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="FIG.&nbsp;6&nbsp;— The small difference in mean game length hides differences in both tails. Panel (a) shows that unevaluated games are more common among both very short and very long games; the two means sit only 3.5 plies apart despite that. Panel (b) shows the resulting cumulative distributions, whose separation corresponds to a Wasserstein distance of 6.8 plies."><img src="images/fig4_why_distributions.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ecdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;6&nbsp;— The small difference in mean game length hides differences in both tails. Panel (a) shows that unevaluated games are more common among both very short and very long games; the two means sit only 3.5 plies apart despite that. Panel (b) shows the resulting cumulative distributions, whose separation corresponds to a Wasserstein distance of 6.8 plies.
</figcaption>
</figure>
</div>
<p>The cumulative curves make the difference visible. Unevaluated games are more common at both extremes, so the curves cross rather than staying apart in one consistent direction.</p>
<p>One way to summarize that overall separation is the <strong>Wasserstein distance</strong>. In one dimension it is the area between the two cumulative distribution curves, measured in the same units as the variable itself — here, plies. Its value is 6.8 plies, against an absolute difference in means of only 3.5.</p>
<p>The two numbers answer different questions. The mean difference lets discrepancies in opposite directions cancel; the Wasserstein distance measures separation across the whole distribution without that cancellation.</p>
</div>
</div>
</div>
<p>This is the second time a simple summary has hidden the more important structure. With rating, pooling across time controls concealed opposing gradients; with game length, averaging over both tails concealed a hump. Neither summary was wrong, but neither captured the selection pattern we actually care about.</p>
<p>So far, those patterns have been described rather than corrected. The next question is, naturally, whether the information recorded for each game is enough to reweight the evaluated subset so that it more closely resembles the full month.</p>
</section>
<section id="can-weighting-repair-the-evaluated-subset" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="can-weighting-repair-the-evaluated-subset">5. Can weighting repair the evaluated subset?</h2>
<p>As the previous sections showed, the evaluated subset contains too much slow chess, too few tournament games, lower-rated games, and a different length distribution. Weighting offers a possible repair: give underrepresented games more influence and overrepresented games less, until the evaluated subset more closely resembles the full month.</p>
<p>The ultimate goal is not to recover time control, rating, or the other fields already recorded for all 14.3 million games. We already know their full-month values. The goal is to estimate quantities available only for evaluated games (such as blunder rates or changes in engine advantage) and extrapolate from the evaluated subset as if evaluations had been available for the entire month.</p>
<section id="how-weighting-reconstructs-the-population" class="level3">
<h3 class="anchored" data-anchor-id="how-weighting-reconstructs-the-population">How weighting reconstructs the population</h3>
<p>Imagine two groups of 1,000 games each, say 2000–2200 rated Classical games and UltraBullet games. Suppose 20% of the Classical games are analyzed, so 200 appear in the evaluated subset, while only 1% of the UltraBullet games are, so just ten appear.</p>
<p>The two groups are equally common in this imagined month, but the evaluated subset contains them in a ratio of 200 to 10. Left uncorrected, the first group would have twenty times as much influence simply because its games were analyzed more often.</p>
<p>Weighting reverses that distortion. The 200 analyzed Classical games came from a population of 1,000, so each represents <span class="math inline">\(1{,}000/200 = 5\)</span> games: itself and, on average, four similar games without evaluations. Giving each a weight of five restores the group’s total representation because <span class="math inline">\(200 \times 5 = 1{,}000\)</span>.</p>
<p>The ten analyzed UltraBullet games must represent their entire population of 1,000, so each receives a weight of <span class="math inline">\(1{,}000/10 = 100\)</span>. Its weighted total is likewise <span class="math inline">\(10 \times 100 = 1{,}000\)</span>. The original 200-to-10 imbalance has become 1,000 to 1,000, matching the full population.</p>
<p>This is the logic of <strong>inverse-probability weighting</strong><a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>. For an analyzed game <span class="math inline">\(i\)</span>,</p>
<p><span class="math display">\[
w_i=\frac{1}{\hat{\pi}_i},
\qquad
\hat{\pi}_i=
\widehat{P}
\bigl(
\text{evaluated}
\mid
\text{time control, rating, length, tournament}
\bigr)
\]</span></p>
<p>A game estimated to have a 20% probability of being analyzed receives weight <span class="math inline">\(1/0.20 = 5\)</span>; one with a 1% probability receives weight <span class="math inline">\(1/0.01 = 100\)</span>. If the probabilities are estimated adequately and every relevant kind of game retains some analyzed examples, these weighted games reproduce the population’s composition in expectation.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What does reweighting assume about unevaluated games?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Weighting does not create engine evaluations for games that lack them. It only lets an evaluated game stand in for similar unevaluated games.</p>
<p>For that to be useful, games that look alike on the modeled characteristics must also be comparable on the engine-derived outcome we care about. Suppose two otherwise similar games differ because one contained a dramatic blunder — and that blunder is itself what made the game more likely to be analyzed. Weighting on rating, time control, length, and tournament status would not remove the resulting difference in blunder rates.</p>
<p>In other words, after conditioning on the variables used for weighting, whether a game was evaluated should not still depend on the unobserved outcome we are trying to estimate. This is the <strong>missing-at-random assumption</strong>.</p>
</div>
</div>
</div>
</section>
<section id="estimating-the-analysis-probabilities" class="level3">
<h3 class="anchored" data-anchor-id="estimating-the-analysis-probabilities">Estimating the analysis probabilities</h3>
<p>I estimate each game’s analysis probability with a <strong>logistic regression</strong><a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> fitted to all 14,306,375 games. The model uses time control, a rating band (2000–2200, for example) rather than the exact average rating, a game-length band, tournament status, and a time-control × rating interaction — as we saw earlier, higher-rated games are analyzed less often in fast chess but more often in slow chess, so the interaction is needed.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
</section>
<section id="what-can-the-reconstruction-test" class="level3">
<h3 class="anchored" data-anchor-id="what-can-the-reconstruction-test">What can the reconstruction test?</h3>
<p>What I ultimately want to know is whether weighting also reduces bias in engine-derived quantities such as blunder rates. Unfortunately those quantities are unavailable for unevaluated games, so their full-population values are unknown and the accuracy of the fix cannot be checked against them directly. I therefore cannot observe directly how much of their selection bias the weighting removes.</p>
<p>What I can do instead is build an indirect test using variables that are observed for every game. Time control, rating, game length, and tournament status were used to construct the weights. Other variables — game result, termination, and the players’ monthly game counts — were deliberately left out of the model. These are the <strong>prespecified holdout variables</strong><a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>. After weighting, I then asked whether these unseen variables moved toward their known full-month values.</p>
<p>If weighting only fixes the variables it was explicitly built to balance, that tells us little about outcomes the model never sees. If it also improves the variables deliberately withheld from the model, that is stronger evidence that the model captures broader selection structure, and therefore more encouraging for the unobserved engine-derived outcomes that cannot be tested directly.</p>
</section>
<section id="testing-the-adjustment" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="testing-the-adjustment">Testing the adjustment</h3>
<div id="fig-weighting" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-weighting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<a href="images/F5_correction.png" class="lightbox page-columns page-full" data-gallery="quarto-lightbox-gallery-7" title="FIG.&nbsp;7&nbsp;— Weighting nearly restores the variables used to build the model, but only partly improves variables it never saw. Each row shows the evaluated-subset value moving toward the known full-month target after weighting; farther movement toward the target means more of the original discrepancy has been removed. The upper rows are model inputs and mainly serve as a diagnostic, while the lower rows are prespecified holdouts and provide the more meaningful test of generalization. Categories with little or no evaluated support cannot be meaningfully repaired."><img src="images/F5_correction.png" class="img-fluid figure-img column-page-inset"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-weighting-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;7&nbsp;— Weighting nearly restores the variables used to build the model, but only partly improves variables it never saw. Each row shows the evaluated-subset value moving toward the known full-month target after weighting; farther movement toward the target means more of the original discrepancy has been removed. The upper rows are model inputs and mainly serve as a diagnostic, while the lower rows are prespecified holdouts and provide the more meaningful test of generalization. Categories with little or no evaluated support cannot be meaningfully repaired.
</figcaption>
</figure>
</div>
<p>The upper half of <a href="#fig-weighting" class="quarto-xref">Figure&nbsp;7</a> is mainly a sanity check. Weighting nearly restores the variables used to build the model: Classical games move from 5.57% of the evaluated subset to 1.71%, close to their 1.68% share of the full month. The 41-point rating gap falls to about half a point, and 89% of the tournament gap closes. This is reassuring but not surprising — the weights were explicitly constructed from these variables.</p>
<p>Game length is the instructive exception among them. Although length appears in the model, weighting closes only 72% of its gap, because length enters through seven broad bins (81–120 plies, say, rather than an exact count of 96): the model can restore how many games fall in each bin without correcting the differences among games inside the same bin. Bin width is not the whole story, though. A truncation check in the appendix shows that capping the largest 1% of weights raises this figure to 89%, so a few extreme weights carry part of the residual gap too.</p>
<p>The more informative test is the lower half, containing variables the model never saw. Here the correction is much weaker. Across the prespecified holdout checks with enough evaluated games to reweight, weighting removes only 29–47% of the original discrepancies: participants’ monthly game counts improve by 41%, the major termination gaps by 44–47%, and the draw gap by 43%. The low end of that range is the black-win share, which started out only 2.7% off; when the initial gap is that small, the percentage closed is itself an unstable number.</p>
<p>Why do omitted variables move at all? Because they are related to variables that were included. Time forfeits, for example, are more common in fast chess, so correcting the mix of time controls also moves the termination distribution in the right direction, even though termination itself was never used to construct the weights.</p>
<p>But the correction stops well short of the target. More than half of each fixable holdout discrepancy remains. The adjustment therefore generalizes beyond its own inputs, but only partially. The remaining gaps could come from a model that is too coarse, from omitted interactions, or from selection tied to information not recorded in the game-level data; this test cannot distinguish among those possibilities.</p>
</section>
<section id="where-weighting-fails" class="level3">
<h3 class="anchored" data-anchor-id="where-weighting-fails">Where weighting fails</h3>
<p>Weighting has two important limits.</p>
<p>First, it cannot recover groups that are essentially absent from the evaluated subset. None of the 7,592 games recorded as Unterminated carries an evaluation, so there is nothing to reweight and the discrepancy closes by exactly 0.0%. Abandoned games present a softer version of the same problem: roughly 59,000 exist in the full month, but only about forty are evaluated, and weighting closes just 0.2% of the gap. For weighting to work at all, the evaluated subset must contain enough examples of each relevant type to represent the missing ones. This is the <strong>overlap condition</strong>, also called positivity.</p>
<p>Second, weighting can occasionally make an already-small discrepancy worse. Games ending through a rules infraction are extremely rare (about seven in every 100,000), and the unweighted evaluated subset already matches their population share closely. After weighting, the estimate moves away from the benchmark, rising to nearly twice it with an interval that excludes the true value. The category is too rare to matter substantively here, but the failure mode matters.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why can a correction make an estimate worse?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Weighting is designed to repair the variables used to construct the weights. It does not guarantee that every other variable moves closer to its population value.</p>
<p>Consider the rare rules-infraction category. Before weighting, its share in the evaluated subset already sat close to the full-month value. Reweighting changed which kinds of games carried more influence, and a few heavily weighted games in this tiny category pushed the estimate away from the benchmark.</p>
<p>This is easiest to happen for rare outcomes, where a weighted estimate may rest on only a handful of observations. Truncating the largest weights reduces the distortion in this example, while the main holdout results stay much more stable; weight distributions, effective sample size, and the truncation check appear in the appendix.</p>
<p>Weighting is therefore not a guarantee of improvement for every quantity. Its performance has to be checked on the outcomes a study actually cares about.</p>
</div>
</div>
</div>
<p>The broader result is therefore limited but useful: weighting makes the evaluated subset more representative on many observed dimensions, but it cannot make the subset equivalent to the full population. The remaining gaps suggest that some important selection structure is missing from the game-level variables.</p>
<p>Since analysis requests are made by people, the next natural question is whether knowing who played the game explains some of what the game itself does not.</p>
</section>
</section>
<section id="analysis-clusters-around-players" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="analysis-clusters-around-players">6. Analysis clusters around players</h2>
<p>Section 5 left one particularly suggestive mismatch. Even after weighting on recorded game characteristics, much of the discrepancy in the participants’ monthly activity remained. That was a clue that the selection model might be operating at the wrong level.</p>
<p>Every predictor in that model described the game: its time control, rating, length, or tournament status. But an evaluation enters the file only after someone requests it.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> That human choice may be associated not only with what kind of game it is, but also with whose game it is. The next question was therefore whether evaluations repeatedly land on games involving the same participants.</p>
<p>The most direct participant-level signal available in the data is the evaluation history of the participants’ other games. For each game, I calculated the share of each player’s <em>other</em> games that month that carried an evaluation, then averaged the two players’ rates. I call the result the game’s <strong>participant-history score</strong><a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a>. It is an evaluation percentage, not a measure of how many games the players played.</p>
<p>The current game is excluded from both players’ rates. This <strong>leave-one-out</strong> rule prevents the game’s own evaluation status from entering the variable used to predict it. “History” is also only shorthand: the score summarizes the full month, so some of the other games may have occurred later than the focal game. It is a retrospective measure of clustering, not a forecasting variable.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why must the current game be left out?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>If the current game were included in its players’ analysis histories, its own outcome would partly determine the predictor used to predict it. An evaluated game would push its history score upward; an unevaluated game would push it downward. The model would be handed a small piece of the answer in advance. This is <strong>target leakage</strong>, not genuine predictive information.</p>
<p>Leaving the current game out removes that direct feedback. The idea is similar to a deleted studentized residual, where an observation is assessed using a model fitted without that observation.</p>
<p>This does not make participant history a forecasting variable: it still summarizes other games from the same month, including games that may have occurred later. Leave-one-out simply ensures that a game does not help predict itself.</p>
</div>
</div>
</div>
<div id="fig-history" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-history-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/F6b_habit_gradient.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="FIG.&nbsp;8&nbsp;— Analysis is strongly concentrated among games involving participants whose other games are also frequently evaluated. Across participant-history bins the rate rises from 1.7% to 79.5%, a 47-fold range. Participant history summarizes the two players’ leave-one-out analysis rates among their other games that month; the denominator is all games in each bin. Two small or structurally ambiguous bins are omitted, with exact counts in Table&nbsp;8."><img src="images/F6b_habit_gradient.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-history-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;8&nbsp;— Analysis is strongly concentrated among games involving participants whose other games are also frequently evaluated. Across participant-history bins the rate rises from 1.7% to 79.5%, a 47-fold range. Participant history summarizes the two players’ leave-one-out analysis rates among their other games that month; the denominator is all games in each bin. Two small or structurally ambiguous bins are omitted, with exact counts in <a href="#tbl-c4" class="quarto-xref">Table&nbsp;8</a>.
</figcaption>
</figure>
</div>
<p>The raw gradient is striking. Analysis rates varied 5.9-fold across time controls and 16-fold across game-length groups, but across participant-history groups, they vary from 1.7% to 79.5%, a 47-fold range. These ranges are not a causal comparison or a formal ranking of variable importance. They show that evaluations are far more concentrated around participants than the earlier game-level summaries revealed.</p>
<p>The raw gradient alone cannot tell us whether participant history contains genuinely new information. Players with high history scores might simply play more Classical games, occupy different rating bands, or produce games of different lengths. To separate participant history from those recorded game characteristics, I added the score, in bins, to the selection model from Section 5.</p>
<p>I compared the two models using the <strong>AUC</strong><a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a>, which asks how well a model ranks evaluated games above unevaluated ones. It is a statement about ordering, not about labelling any individual game correctly.</p>
<p>Using only time control, rating, length, and tournament status, the model has an in-sample AUC of 0.664 (95% CI 0.662–0.665): it identifies the evaluated game about two times in three. Adding the participant-history score raises the AUC to 0.827 (95% CI 0.826–0.828), or roughly five times in six. Participant history therefore carries substantial information about where evaluations appear, beyond everything contained in the modeled game characteristics.</p>
<p>This is an incremental comparison. It measures what participant history adds to the game-feature model, not how well participant history would perform by itself—a model I did not run. It is also retrospective within-month discrimination, not evidence that the model could forecast which future games will be analyzed.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why compare the models with AUC rather than accuracy?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Only 7.54% of games are evaluated. A model that predicts “not evaluated” for every game would therefore be 92.46% accurate while learning nothing about which games actually receive evaluations. Accuracy would mostly reward the class imbalance.</p>
<p>AUC avoids that by asking a ranking question: if we pick one evaluated and one unevaluated game, how often does the model rank the evaluated one higher? That suits the question here, where I want to know whether adding participant history helps separate the two groups — without having to choose an arbitrary classification threshold.</p>
<p>A higher AUC means better discrimination. It does not mean the model has explained the selection process, established causality, produced well-calibrated probabilities, or yielded better inverse-probability weights. Here I use it only to compare how much discriminatory information the two sets of predictors contain.</p>
</div>
</div>
</div>
<section id="the-time-control-hierarchy-nearly-disappears" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="the-time-control-hierarchy-nearly-disappears">The time-control hierarchy nearly disappears</h3>
<p>The AUC result shows that participant history adds information. What is more revealing is what happens to the time-control pattern once that information enters the model.</p>
<p>In the game-feature model, a Classical game had 4.7 times the odds of analysis of a comparable Blitz game. After adding participant history, that <strong>odds ratio</strong><a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a> falls to 0.99 (95% CI 0.96–1.02). Among games with similar recorded characteristics and participant histories, Classical is therefore no more likely to be analyzed than Blitz.</p>
<p>This sharply changes the interpretation of the raw pattern. Classical chess is overrepresented 3.3-fold in the evaluated subset, which initially looked like a feature of slow chess itself. But most of that Classical–Blitz difference disappears once players’ prior analysis behavior is taken into account. Bullet (1.06 to 1.00) and Rapid (1.59 to 0.96) show the same collapse toward Blitz, while UltraBullet (to 1.50, 95% CI 1.41–1.60) and Correspondence (to 0.59, 0.55–0.63) move past it in opposite directions.</p>
<p>This does not prove that time control has no independent role. Participant history is a noisy proxy, especially for players with few other games, and it can absorb many differences between players.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> But it shows that much of the apparent time-control hierarchy is associated with who plays and analyzes those games, not just with the games’ recorded features.</p>
<div id="fig-players" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-players-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<a href="images/F6_player.png" class="lightbox page-columns page-full" data-gallery="quarto-lightbox-gallery-9" title="FIG.&nbsp;9&nbsp;— Adding participant history substantially improves discrimination and reshapes the apparent time-control differences. Left: in-sample AUC rises from 0.664 to 0.827. Right: after participant history is added, the odds ratios for Classical, Rapid, and Bullet move close to 1, meaning little remaining difference from Blitz at the reference profile, while UltraBullet and Correspondence move to opposite sides of Blitz. Whiskers show 95% player-resampling stability intervals (B = 200)."><img src="images/F6_player.png" class="img-fluid figure-img column-page-inset"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-players-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;9&nbsp;— Adding participant history substantially improves discrimination and reshapes the apparent time-control differences. Left: in-sample AUC rises from 0.664 to 0.827. Right: after participant history is added, the odds ratios for Classical, Rapid, and Bullet move close to 1, meaning little remaining difference from Blitz at the reference profile, while UltraBullet and Correspondence move to opposite sides of Blitz. Whiskers show 95% player-resampling stability intervals (B = 200).
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Does the collapse mean time control itself does not matter?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;The same observed pattern can arise from at least two different causal stories.</p>
<p><strong>World A: player composition.</strong> Suppose some unobserved player characteristic makes people both more likely to choose slower time controls and more likely to analyze their games. Participant history then acts as a <strong>proxy variable</strong><a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a> for that characteristic. Conditioning on it removes a Classical–Blitz difference that was largely associated with <em>who</em> played the two formats, rather than with the formats themselves.</p>
<p><strong>World B: overadjustment.</strong> Suppose playing Classical itself makes a game more likely to be analyzed. If players also tend to specialize in particular time controls, their other games carry some of that same format-related pattern. Participant history would then partly reflect the very relationship we are trying to measure, so conditioning on it removes part of that relationship — an instance of <strong>overadjustment</strong><a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a>.</p>
<div id="fig-two-worlds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-two-worlds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/fig_two_worlds.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="FIG.&nbsp;10&nbsp;— Two causal structures can produce the same observed pattern. In world A, participant history proxies an unobserved player characteristic associated with both time-control choice and analysis. In world B, time control itself affects analysis, and participant history partly carries that same relationship. Conditioning on history therefore has very different interpretations in the two worlds."><img src="images/fig_two_worlds.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-two-worlds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;10&nbsp;— Two causal structures can produce the same observed pattern. In world A, participant history proxies an unobserved player characteristic associated with both time-control choice and analysis. In world B, time control itself affects analysis, and participant history partly carries that same relationship. Conditioning on history therefore has very different interpretations in the two worlds.
</figcaption>
</figure>
</div>
<p>Both worlds can produce the same combination of Classical games, high participant-history scores, and higher analysis rates. The observed data therefore cannot tell us which explanation is responsible for the collapse.</p>
<p>Comparing different time controls played by the same people would reduce differences due to stable player characteristics and is a natural next step. It would still not identify a causal effect by itself, because those games may differ in other ways and the dataset does not record who requested the analysis.</p>
</div>
</div>
</div>
<p>The result is descriptive rather than causal. Evaluations are strongly clustered within participants, and as we just saw, adding participant history absorbs much of the association that previously appeared to belong to time control. But the history score could reflect stable review habits, the kinds of time controls those players choose, or some combination of the two.</p>
<p>Nor is participant history a ready-made solution to the weighting problem in Section 5.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a> The score is constructed from the same month’s evaluation outcomes, is noisy for players with few games, and may not be available in another target population. Its main value here is diagnostic: a model based only on game characteristics leaves substantial participant-level selection structure unexplained.</p>
</section>
</section>
<section id="bias-depends-on-what-you-measure" class="level2">
<h2 class="anchored" data-anchor-id="bias-depends-on-what-you-measure">7. Bias depends on what you measure</h2>
<p>There is no single answer to “How biased is the evaluated subset?” The answer depends on what quantity you want to estimate. Some quantities already resemble the full population; some are substantially distorted but can be partly corrected; some categories contain too few evaluated games to recover at all. And for the engine-derived outcomes researchers often care about most, the true population discrepancy cannot be observed from the existing data.</p>
<p>A more useful question is:</p>
<blockquote class="blockquote">
<p>For the quantity I want to estimate, what does the evaluated subset get wrong, and how much can the observed data repair it?</p>
</blockquote>
<div id="tbl-bias-by-quantity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bias-by-quantity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;2&nbsp;— Both the size of selection bias and the success of adjustment depend on the quantity being estimated. Where correction can be evaluated, the final column shows how much game-level weighting moves the evaluated subset toward the full-month benchmark.
</figcaption>
<div aria-describedby="tbl-bias-by-quantity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Target quantity</th>
<th style="text-align: right;">Evaluated subset</th>
<th style="text-align: right;">Full month</th>
<th>Observed distortion</th>
<th>After game-level weighting</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Share of Classical games</td>
<td style="text-align: right;">5.57%</td>
<td style="text-align: right;">1.68%</td>
<td>3.3× too high</td>
<td>Nearly repaired (99% closed)</td>
</tr>
<tr class="even">
<td>Mean rating</td>
<td style="text-align: right;">1580</td>
<td style="text-align: right;">1621</td>
<td>41 points lower</td>
<td>Nearly repaired (99%)</td>
</tr>
<tr class="odd">
<td>Share of tournament games</td>
<td style="text-align: right;">11.3%</td>
<td style="text-align: right;">16.5%</td>
<td>31% too low</td>
<td>Mostly repaired (89%)</td>
</tr>
<tr class="even">
<td>Mean game length</td>
<td style="text-align: right;">64.2 plies</td>
<td style="text-align: right;">67.5 plies</td>
<td>3.2 plies shorter</td>
<td>Mostly repaired (72%)</td>
</tr>
<tr class="odd">
<td>Participants’ monthly games, game-weighted mean</td>
<td style="text-align: right;">368</td>
<td style="text-align: right;">508</td>
<td>28% too low</td>
<td>Partly repaired (41%)</td>
</tr>
<tr class="even">
<td>Share ending by time forfeit</td>
<td style="text-align: right;">26.5%</td>
<td style="text-align: right;">32.8%</td>
<td>6.3 percentage points lower</td>
<td>Partly repaired (47%)</td>
</tr>
<tr class="odd">
<td>Share ending in a draw</td>
<td style="text-align: right;">2.53%</td>
<td style="text-align: right;">3.78%</td>
<td>33% too low</td>
<td>Partly repaired (43%)</td>
</tr>
<tr class="even">
<td>White-win share</td>
<td style="text-align: right;">49.8%</td>
<td style="text-align: right;">49.7%</td>
<td>Essentially none</td>
<td>No correction needed; weighting slightly worsens it</td>
</tr>
<tr class="odd">
<td>Unterminated games</td>
<td style="text-align: right;">0 evaluated games</td>
<td style="text-align: right;">7,592 games (0.05%)</td>
<td>Completely absent</td>
<td>Cannot be repaired: no overlap</td>
</tr>
<tr class="even">
<td>Abandoned games</td>
<td style="text-align: right;">About 40 evaluated games</td>
<td style="text-align: right;">About 59,000 games (0.41%)</td>
<td>Almost absent</td>
<td>Too little overlap for a dependable estimate</td>
</tr>
<tr class="odd">
<td>Engine-derived move quantities, such as blunder rates</td>
<td style="text-align: right;">Observed only for evaluated games</td>
<td style="text-align: right;">Not recorded for the rest</td>
<td>Cannot be measured from the dump</td>
<td>Cannot be validated from the existing annotations</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>The 3.2-ply difference here compares the evaluated subset with the full month. Section 4’s 3.5-ply figure compares evaluated with unevaluated games.</em></p>
<p>The table separates four cases. Variables used to construct the weights, such as time control and rating, are almost fully restored. Recorded variables deliberately withheld from the model improve as well, but only partially: weighting removes about 29–47% of their fixable discrepancies. Categories with little or no evaluated support cannot be reliably reconstructed at all.</p>
<p>The final case is the most important limitation. Engine-derived quantities such as blunder rates and evaluation swings exist only for evaluated games. For unevaluated games there is no full-population benchmark to compare against, so the existing annotations cannot tell us directly how biased those outcomes are, or how much weighting repairs them.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why can’t the existing evaluations reveal their own selection bias?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Suppose we care about the average blunder rate. To measure its selection bias directly, we would need to know the blunder rate not only among evaluated games, but also across the full population — or at least in a representative sample of unevaluated games.</p>
<p>But calculating a blunder rate requires engine evaluations, and unevaluated games have none. The benchmark needed to measure the bias is therefore missing for exactly the games that were not selected.</p>
<p>This is a limitation of the available data, not something a different statistical model can solve. To measure the bias directly, a researcher would need to run the engine on additional games — for example, on a probability sample drawn from the unevaluated population.</p>
</div>
</div>
</div>
<section id="a-practical-workflow" class="level3">
<h3 class="anchored" data-anchor-id="a-practical-workflow">A practical workflow</h3>
<p>For researchers who use pre-existing evaluations, the results suggest four steps.</p>
<ol type="1">
<li><strong>Report the selected subset clearly.</strong> State how it is defined and what fraction of the original games it retains — for example, “We use the 7.5% of games carrying pre-existing evaluations.” None of the nine studies I inspected reported that share.<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></li>
<li><strong>Compare it with the full population on variables observed for every game.</strong> Time control, rating, game length, tournament status, result, and termination provide inexpensive checks for obvious selection differences. The accompanying tables make these comparisons straightforward for November 2017; the same checks can be rerun for another month.</li>
<li><strong>Check overlap before weighting.</strong> If an important category contains few or no evaluated games, reweighting cannot make it representative — the overlap condition from Section 5.</li>
<li><strong>Test adjustment on variables the model did not use.</strong> Matching the variables that constructed the weights is expected; improvement on withheld variables is a more informative test. For engine-derived outcomes that remain unobserved outside the evaluated subset, the remaining bias should be treated as unknown rather than assumed away.</li>
</ol>
</section>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">8. Limitations</h2>
<section id="the-most-important-outcomes-remain-unobserved" class="level3">
<h3 class="anchored" data-anchor-id="the-most-important-outcomes-remain-unobserved">The most important outcomes remain unobserved</h3>
<p>The central limitation is built into the data. Engine-derived quantities such as blunder rates and evaluation swings exist only for games that were analyzed. For the unevaluated games, there is no full-population benchmark against which to measure their selection bias or test whether weighting removes it.</p>
<p>The holdout tests provide indirect evidence only. They show that game-level weighting generalizes somewhat beyond the variables used to construct it, but they cannot establish how well the same adjustment works for unobserved engine outcomes. Answering that question directly would require running an engine on additional unevaluated games.</p>
</section>
<section id="one-month-on-one-platform" class="level3">
<h3 class="anchored" data-anchor-id="one-month-on-one-platform">One month on one platform</h3>
<p>This study is a detailed case study of Lichess in November 2017. A single month is also what one laptop can process end to end, which is why the design is a deep audit of one month rather than a shallow pass over many. The month was not sampled to represent other periods, and a selection process observed in 2017 should not be assumed to describe current Lichess behavior. Nor do the results establish that other chess platforms generate evaluated games in the same way.</p>
<p>The clearest replication would be to rerun the same pipeline on a recent month and compare the resulting selection patterns.</p>
</section>
<section id="participant-history-is-a-proxy-not-a-causal-explanation" class="level3">
<h3 class="anchored" data-anchor-id="participant-history-is-a-proxy-not-a-causal-explanation">Participant history is a proxy, not a causal explanation</h3>
<p>The participant-history score summarizes how often a player’s other games were evaluated. It is not a direct measure of a stable review habit, and it is noisy for players with few other games. The dataset also does not identify who requested each analysis. A synthetic check reported in the appendix shows that this noise causes the observed score to absorb only part of a pattern created entirely by player composition; it validates the implementation under one known scenario and says nothing about the direction or size of measurement error in the real data.</p>
<p>For the same reason, the collapse of the time-control hierarchy after adding participant history should be interpreted descriptively rather than causally. The pattern could arise because different kinds of players choose different formats, because formats influence analysis behavior, or through both mechanisms. Comparing slow and fast games played by the same people would sharpen the distinction, though it would not by itself identify a causal effect.</p>
<p>A related caution applies to rating: Lichess maintains separate rating pools across time controls, so the same numerical rating does not necessarily represent the same underlying playing strength across formats.</p>
</section>
<section id="adjustment-depends-on-the-model-specification" class="level3">
<h3 class="anchored" data-anchor-id="adjustment-depends-on-the-model-specification">Adjustment depends on the model specification</h3>
<p>The weighting model uses categorical bins and a prespecified rating × time-control interaction. This avoids forcing a single linear relationship, but it also treats games within the same bin as equivalent. The remaining game-length discrepancy shows that this coarseness can matter.</p>
<p>More flexible specifications — narrower bins, splines, or additional interactions — might improve adjustment, but they would introduce further modeling choices, and alternative bin boundaries were not tested. The robustness checks reported in the appendix show that removing Correspondence, the most structurally unusual time control, does not materially change the main results, but they do not exhaust all plausible specifications.</p>
</section>
<section id="the-intervals-measure-stability-not-uncertainty-about-missing-games" class="level3">
<h3 class="anchored" data-anchor-id="the-intervals-measure-stability-not-uncertainty-about-missing-games">The intervals measure stability, not uncertainty about missing games</h3>
<p>The November 2017 dump is a complete enumeration of the target month, so the descriptive point values are population quantities for that month rather than estimates from a random sample of games.</p>
<p>The intervals in this article instead use player-level resampling to show how sensitive the results are to dependence and player composition. Their construction and crossed-player checks appear in the appendix. They should therefore be read as stability intervals, not as uncertainty about unseen November games. Likewise, all reported AUCs are in-sample and should not be interpreted as forecasting performance.</p>
</section>
</section>
<section id="conclusion-selection-is-about-both-games-and-players" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-selection-is-about-both-games-and-players">9. Conclusion: selection is about both games and players</h2>
<p>This project began with a simple question: if researchers use the Lichess games that already contain engine evaluations, are they looking at a representative slice of chess?</p>
<p>The answer is no, at least for November 2017. The evaluated games differ systematically from the full month, and several of those differences are easy to miss with simple summaries. Rating behaves differently in fast and slow chess; game length has a strong hump-shaped relationship with analysis even though the mean difference is small; and much of the apparent time-control pattern changes once participants’ previous analysis history is taken into account. Participant history adds substantial information about where evaluations appear beyond the recorded characteristics of the games themselves.</p>
<p>That does not make the evaluated games bad data. It makes them selected data. Game-level weighting can remove much of the discrepancy on variables it was built to balance, and some of the discrepancy on variables it never saw. But the correction is incomplete. It cannot recover categories with little or no evaluated support, and it cannot directly validate engine-derived outcomes such as blunder rates, because those outcomes are unobserved for the games outside the subset.</p>
<p>The distinction that matters is therefore between how the engine evaluates a game and how that game comes to be evaluated in the first place. The engine may apply the same procedure once a game reaches it, but the sample reaching it has already been shaped by human choices. In this dataset, those choices are structured not only by properties of the games, but also by the people who play and analyze them.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-cuvitoglu2026" class="csl-entry" role="listitem">
Cüvitoğlu, Ali. 2026. <span>“Interpretable Machine Learning Analysis of Nonlinear Error Amplification Under Time Pressure and Positional Ambiguity in Elite Blitz Chess.”</span> <em>Scientific Reports</em>, ahead of print, June. <a href="https://doi.org/10.1038/s41598-026-59689-z">https://doi.org/10.1038/s41598-026-59689-z</a>.
</div>
<div id="ref-elbert2026" class="csl-entry" role="listitem">
Elbert, Nico, Philipp Landeck, and Christoph Flath. 2026. <span>“From Engine-Optimal to Human-Optimal: Designing Behavior-Grounded <span>AI</span> Training Systems.”</span> <em><span>ECIS</span> 2026 Proceedings</em>. <a href="https://aisel.aisnet.org/ecis2026/esports/esports/5">https://aisel.aisnet.org/ecis2026/esports/esports/5</a>.
</div>
<div id="ref-mcilroyyoung2020" class="csl-entry" role="listitem">
McIlroy-Young, Reid, Siddhartha Sen, Jon Kleinberg, and Ashton Anderson. 2020. <span>“Aligning Superhuman <span>AI</span> with Human Behavior: Chess as a Model System.”</span> <em>Proceedings of the 26th <span>ACM</span> <span>SIGKDD</span> International Conference on Knowledge Discovery &amp; Data Mining (<span>KDD</span> ’20)</em>. <a href="https://doi.org/10.1145/3394486.3403219">https://doi.org/10.1145/3394486.3403219</a>.
</div>
</div>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">Appendix</h2>
<p>The appendix is organised as an audit layer rather than a second version of the article. Appendix A defines what was analysed, B specifies the methods, C reports what happened when those methods were stress-tested, D gives the exact numbers and their provenance, and E covers data, code, and AI assistance.</p>
<section id="a.-data-scope-and-analysis-definitions" class="level3">
<h3 class="anchored" data-anchor-id="a.-data-scope-and-analysis-definitions">A. Data scope and analysis definitions</h3>
<section id="population-and-unit-of-analysis" class="level4">
<h4 class="anchored" data-anchor-id="population-and-unit-of-analysis">Population and unit of analysis</h4>
<p>The target population is the November 2017 Lichess database of standard rated games, <code>lichess_db_standard_rated_2017-11.pgn</code>. The unit of analysis throughout the article is a single game. Chess variants are published by Lichess in separate files and casual games are not included in this database, so neither requires an additional exclusion.</p>
<p>The parser was specified to drop records whose player-rating fields are not numeric. After that exclusion 14,306,375 games remain, and every quantity in the article is computed on that set.</p>
</section>
<section id="evaluated-game-indicator" class="level4">
<h4 class="anchored" data-anchor-id="evaluated-game-indicator">Evaluated-game indicator</h4>
<p>A game is classified as evaluated if its movetext contains at least one <code>[%eval ...]</code> annotation; the indicator <code>has_eval</code> is 1 for such games and 0 otherwise.</p>
<p>This definition measures whether an evaluation was present when the monthly dump was created. A game analysed only later would still appear as unevaluated in this static file.</p>
<p>The database records the presence of an evaluation but not who requested it. The requester may be one of the two players or another person viewing the game afterwards, so <code>has_eval</code> is treated as a game-level selection indicator rather than as an observed decision by a particular player.</p>
</section>
<section id="recorded-game-characteristics" class="level4">
<h4 class="anchored" data-anchor-id="recorded-game-characteristics">Recorded game characteristics</h4>
<div id="tbl-a1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-a1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;3&nbsp;— Operational definitions of the recorded game characteristics used throughout the article. Time control is taken from the clock settings rather than inferred from the event name.
</figcaption>
<div aria-describedby="tbl-a1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Operational definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Game rating</strong></td>
<td>Mean of the two players’ pre-game ratings, <span class="math inline">\((\text{WhiteElo}+\text{BlackElo})/2\)</span></td>
</tr>
<tr class="even">
<td><strong>Time control</strong></td>
<td>Lichess’s category, derived from the estimated duration <code>base + 40 × increment</code>: under 30 s UltraBullet, under 180 s Bullet, under 480 s Blitz, under 1500 s Rapid, otherwise Classical; a <code>-</code> clock field denotes Correspondence</td>
</tr>
<tr class="odd">
<td><strong>Game length</strong></td>
<td>Number of plies, where one ply is one move by one player</td>
</tr>
<tr class="even">
<td><strong>Tournament status</strong></td>
<td>Indicator that the PGN <code>Event</code> field contains <code>tournament</code></td>
</tr>
<tr class="odd">
<td><strong>Result</strong></td>
<td>White win, Black win, or draw, from the PGN result field</td>
</tr>
<tr class="even">
<td><strong>Termination</strong></td>
<td>Recorded termination category: Normal, Time forfeit, Abandoned, and the rarer categories retained in the data</td>
</tr>
<tr class="odd">
<td><strong>Participants’ monthly games</strong></td>
<td>For each game, the average number of games played that month by its two participants</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="what-is-observed-for-the-full-population" class="level4">
<h4 class="anchored" data-anchor-id="what-is-observed-for-the-full-population">What is observed for the full population</h4>
<p>Time control, ratings, game length, tournament status, result, termination, and participant activity are recorded for evaluated and unevaluated games alike. These variables therefore have known full-month benchmarks against which the evaluated subset can be compared, which is what makes the audit in §5 and §7 possible at all.</p>
<p>Engine-derived move quantities are different. Position evaluations, evaluation swings, blunder rates and the like exist only where engine annotations are present. Their full-population values cannot be recovered from this dump, which is the limitation §8 returns to.</p>
</section>
</section>
<section id="b.-statistical-methods" class="level3">
<h3 class="anchored" data-anchor-id="b.-statistical-methods">B. Statistical methods</h3>
<p>This section specifies what was done. What happened when each procedure was checked is reported separately in Appendix C.</p>
<section id="b.1-stability-intervals-and-player-clustering" class="level4">
<h4 class="anchored" data-anchor-id="b.1-stability-intervals-and-player-clustering">B.1 Stability intervals and player clustering</h4>
<p>November 2017 is treated as a complete finite population rather than as a random sample of games. The descriptive point values in the article are therefore exact quantities for that month, carrying no sampling error. The reported intervals answer a different question: how much would those quantities move under a different draw of the month’s players, given that games involving the same players are not independent? Repeat pairings are common — 41.5% of games involve a player pair that appears more than once — so treating 14.3 million games as 14.3 million independent observations would badly overstate precision.</p>
<p>Unless otherwise noted, 95% intervals come from a one-way player bootstrap. The 276,345 players are resampled with replacement, each game is weighted by how often its designated player appears in the resample, and the entire statistic is recomputed. The procedure is run twice, once with each game assigned to its White player and once to its Black player, with B = 200 replicates per seat; the wider of the two intervals is reported.</p>
<p>For statistics involving a fitted model, the model is refit inside every replicate rather than holding the original coefficients fixed. Ratio statistics are combined on the log scale and transformed back afterwards. Quantities that describe a player’s month as a whole — participants’ monthly game counts, and the participant-history score of §6 — are measured once on the real data and carried into the replicates as fixed game-level covariates rather than being re-derived inside each resample.</p>
<p>These intervals are called <strong>stability intervals</strong> rather than confidence intervals because they do not express uncertainty about unobserved November games: the month is fully observed. They can equally be read as superpopulation confidence intervals under an independent-player sampling model, but nothing in the article depends on that second reading. Wilson intervals are used instead for a small number of sparse binomial cells, where the purpose is to display the instability caused by very small counts rather than to describe player-level stability.</p>
</section>
<section id="b.2-kitagawa-decomposition" class="level4">
<h4 class="anchored" data-anchor-id="b.2-kitagawa-decomposition">B.2 Kitagawa decomposition</h4>
<p>To separate the 41-point rating gap into a part associated with differences in time-control composition and a part remaining within time controls, I use a symmetric Kitagawa decomposition.</p>
<p>Let <span class="math inline">\(w_c^{\mathrm{ev}}\)</span> and <span class="math inline">\(w_c^{\mathrm{all}}\)</span> denote the share of control <span class="math inline">\(c\)</span> in the evaluated subset and in the full month, and <span class="math inline">\(m_c^{\mathrm{ev}}\)</span> and <span class="math inline">\(m_c^{\mathrm{all}}\)</span> their mean game ratings. The total gap is</p>
<p><span class="math display">\[\Delta=\sum_c w_c^{\mathrm{ev}}m_c^{\mathrm{ev}}-\sum_c w_c^{\mathrm{all}}m_c^{\mathrm{all}}.\]</span></p>
<p>Using midpoint weights this can be written exactly as</p>
<p><span class="math display">\[\underbrace{\sum_c\bigl(w_c^{\mathrm{ev}}-w_c^{\mathrm{all}}\bigr)\tfrac{m_c^{\mathrm{ev}}+m_c^{\mathrm{all}}}{2}}_{\text{composition}}\;+\;\underbrace{\sum_c\tfrac{w_c^{\mathrm{ev}}+w_c^{\mathrm{all}}}{2}\bigl(m_c^{\mathrm{ev}}-m_c^{\mathrm{all}}\bigr)}_{\text{within}}\;=\;\Delta.\]</span></p>
<p>The first term measures how much of the rating gap is associated with the evaluated subset containing a different mix of time controls; the second measures the rating differences that remain within those controls. The identity is asserted at runtime, and the group means are computed from lossless counts rather than from rounded summaries.</p>
<p>This symmetric convention does not privilege either group as the baseline. Sequential conventions — weighting composition by baseline means, or by evaluated-set means — allocate the total somewhat differently, so the reported 24.2% composition share should be read as the allocation under this stated convention rather than as a unique decomposition.</p>
</section>
<section id="b.3-selection-model-and-inverse-probability-weighting" class="level4">
<h4 class="anchored" data-anchor-id="b.3-selection-model-and-inverse-probability-weighting">B.3 Selection model and inverse-probability weighting</h4>
<p>For each game <span class="math inline">\(g\)</span>, let <span class="math inline">\(S_g = 1\)</span> if the game carries an evaluation and <span class="math inline">\(0\)</span> otherwise. I estimate <span class="math inline">\(\pi_g = P(S_g = 1 \mid X_g)\)</span> with an unpenalised logistic regression:</p>
<p><span class="math display">\[\operatorname{logit}(\pi_g)=\alpha+\beta_{\text{control}}+\beta_{\text{rating band}}+\beta_{\text{length band}}+\beta_{\text{tournament}}+\gamma_{\text{control}\times\text{rating}}.\]</span></p>
<p>The predictors are time control, game-rating band, game-length band, tournament status, and a time-control × rating interaction. The interaction is included because the relationship between rating and evaluation reverses across time controls.</p>
<p>Rating is grouped into 200-point bands through the central range, with open-ended groups below 1000 and above 2400. Game length uses the same seven categories as the main analysis: 0–10, 11–20, 21–40, 41–60, 61–80, 81–120, and more than 120 plies. The reference profile is a non-tournament Blitz game rated 1400–1600 and lasting 41–60 plies; because the model contains an interaction, main effects are contrasts at those reference conditions. The fit is an unpenalised maximum-likelihood fit by iteratively reweighted least squares, with 59 parameters over 654 populated predictor cells.</p>
<p>For each evaluated game the inverse-probability weight is <span class="math inline">\(w_g = 1/\hat{\pi}_g\)</span>, so games the model judged unlikely to be evaluated stand in for more of the population. For a quantity <span class="math inline">\(Y\)</span> observed among evaluated games, the weighted estimate is</p>
<p><span class="math display">\[\hat{\mu}_{w}=\frac{\sum_{g:S_g=1}w_gY_g}{\sum_{g:S_g=1}w_g},\]</span></p>
<p>where <span class="math inline">\(Y_g\)</span> is an indicator of category membership for categorical quantities.</p>
<p>Game result, termination, and participants’ monthly game counts are deliberately excluded from the selection model. Because their full-month values are nevertheless observed, they serve as prespecified holdout variables for testing whether the adjustment generalises beyond the characteristics used to build the weights.</p>
<p>The headline analysis uses the untruncated weights. Sensitivity to large weights and to alternative truncation thresholds is reported in Appendix C.3.</p>
</section>
<section id="b.4-participant-history-construction" class="level4">
<h4 class="anchored" data-anchor-id="b.4-participant-history-construction">B.4 Participant-history construction</h4>
<p>Section 6 introduces a participant-level variable intended to capture clustering in where evaluations appear.</p>
<p>For player <span class="math inline">\(p\)</span>, let <span class="math inline">\(N_p\)</span> be the number of games that player played during the month and <span class="math inline">\(E_p\)</span> the number of those games carrying evaluations. For a focal game <span class="math inline">\(g\)</span> with evaluation indicator <span class="math inline">\(e_g\)</span>, that player’s leave-one-out history rate is</p>
<p><span class="math display">\[h_{pg}=\frac{E_p-e_g}{N_p-1},\]</span></p>
<p>defined whenever the player has at least one other game in the month. Removing the focal game prevents its own evaluation status from entering its own predictor.</p>
<p>The game-level participant-history score is the mean of the leave-one-out rates that are <strong>available</strong> for the two players. When only one player has other games that month, that player’s rate is used alone; the 435 games (0.003%) in which neither player has another game are assigned to a separate no-history category.</p>
<p>For modelling, the score is entered categorically: exactly 0%, 0–5%, 5–10%, 10–20%, 20–50%, 50–100%, and no history, with exactly 0% as the reference. The participant-history model otherwise uses the same game-level predictors and time-control × rating interaction as the selection model above.</p>
<p>The exactly-0% bin deserves a note of its own. It holds 20,706 games and is 3.1% analysed, which is <em>higher</em> than the 1.7% of the 0–5% bin above it. That non-monotonicity is a measurement artefact rather than behaviour: the bin mixes genuine never-analysers with players whose handful of other games makes the rate uninformative.</p>
<p>“History” is shorthand and not a temporal claim. The score uses the participants’ other games from the whole month, including games played after the focal game. It is a retrospective measure of within-player clustering, not a forecasting variable and not a direct measure of any player’s underlying tendency to request analysis.</p>
</section>
</section>
<section id="c.-diagnostics-and-robustness" class="level3">
<h3 class="anchored" data-anchor-id="c.-diagnostics-and-robustness">C. Diagnostics and robustness</h3>
<p>Appendix B states what the procedures are. This section reports what happened when they were checked against clustering, extreme weights, an unusual time control, and the construction of the participant-history score. Except where an interval is quoted, the robustness comparisons in C.3 and C.4 are point-value only.</p>
<section id="c.1-interval-and-clustering-checks" class="level4">
<h4 class="anchored" data-anchor-id="c.1-interval-and-clustering-checks">C.1 Interval and clustering checks</h4>
<p>Games are not independent observations because the same players recur, so the main intervals use the player-resampling procedure of Appendix B.1 rather than a game-level bootstrap. Design effects on the headline rates run from roughly 6 to 34, so no single variance-inflation factor would serve.</p>
<p>Two checks support the scheme. As a calibration, the player bootstrap returns a design effect of 12.9 for the overall evaluation rate, close to an independently derived closed-form value of 13.2. A more conservative crossed-player check, which accounts for clustering through the White player, the Black player, and the pairing together, widens the intervals by roughly a factor of 1.4 and changes no substantive conclusion. All bootstrap model refits converged.</p>
<p>These checks support reading the reported intervals as measures of player-level stability, not as sampling error around an unobserved population.</p>
</section>
<section id="c.2-selection-model-and-weight-diagnostics" class="level4">
<h4 class="anchored" data-anchor-id="c.2-selection-model-and-weight-diagnostics">C.2 Selection-model and weight diagnostics</h4>
<p>The game-feature selection model is deliberately low-dimensional relative to the data it is fit on: 59 parameters over 654 populated predictor cells and 14.3 million games.</p>
<p>Most rating × time-control cells are well supported, but two degenerate margins require a fallback, which was fixed in code before any output was inspected: when a margin has no games, no evaluated games, or only evaluated games, its interaction term is dropped and predictions are supplied by the remaining main effects, since the coefficient would otherwise run to a boundary. Two margins trip the rule. Correspondence below rating 1000 contains no games at all this month, so nobody is affected. Classical above 2400 contains exactly two games, both evaluated; those two games’ predictions and weights are served by main effects. At two games in 14.3 million, no headline quantity is sensitive to any reasonable alternative treatment.</p>
<p>The fitted weights are unequal but not dominated by a small tail. The largest weight is about 660, corresponding to a cell evaluated roughly 0.15% of the time. The heaviest 1% of evaluated games carry 4.5% of the total weight. The Kish effective sample size is 753,325, about 70% of the 1,078,379 evaluated games; this measures information loss from unequal weights only, not the additional dependence created by repeated players, which the bootstrap handles separately.</p>
<p>All reported AUCs are computed in-sample. With 14.3 million games against 59 parameters the optimism is negligible, but the figures are used to compare discrimination between specifications, not as estimates of out-of-sample forecasting performance.</p>
</section>
<section id="c.3-sensitivity-to-weight-truncation" class="level4">
<h4 class="anchored" data-anchor-id="c.3-sensitivity-to-weight-truncation">C.3 Sensitivity to weight truncation</h4>
<p>Extreme inverse-probability weights are a standard source of instability, so every weighted quantity was recomputed with the weights winsorised — capped at a threshold, with all smaller weights untouched. Because every target here is a weighted mean or share, capping renormalises automatically. The headline analysis uses the original, untruncated weights.</p>
<div id="tbl-c5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-c5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;4&nbsp;— Weight-truncation rules tested, with the threshold each implies and the number of the 1,078,379 evaluated games whose weight it binds.
</figcaption>
<div aria-describedby="tbl-c5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Truncation rule</th>
<th style="text-align: right;">Maximum allowed weight</th>
<th style="text-align: right;">Evaluated games affected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fixed cap of 200</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">119</td>
</tr>
<tr class="even">
<td>99.9th percentile</td>
<td style="text-align: right;">100.7</td>
<td style="text-align: right;">1,072</td>
</tr>
<tr class="odd">
<td>99th percentile</td>
<td style="text-align: right;">40.8</td>
<td style="text-align: right;">10,776</td>
</tr>
<tr class="even">
<td>95th percentile</td>
<td style="text-align: right;">26.2</td>
<td style="text-align: right;">51,334</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The holdout results of §5 are stable under these alternatives. Under the three milder caps, the closure figures for time forfeits, normal terminations, draws and participants’ monthly game counts each move by less than one percentage point; even the 95th-percentile cap, which binds on 4.8% of the evaluated subset, moves them by at most 4.5 points. The 29% low end of the reported closure range is the black-win share, whose initial discrepancy is only 2.7%; its closure is correspondingly the least stable of the set, at 28.9% untruncated and 18.7% under the 95th-percentile cap.</p>
<p>Two quantities move further, and both clarify rather than undercut the reading in §5. Mean-length closure rises from 72.4% with the original weights to 89.0% under the 99th-percentile cap, which shows that part of the residual length gap is carried by a few very large weights rather than only by the width of the length bins. And the rare rules-infraction category — the case in §5 where weighting makes an already-small discrepancy worse — becomes markedly less distorted as the cap tightens, with closure moving from −234% untruncated to −126% at the 95th percentile. That is direct evidence that the failure is driven by a handful of heavily weighted games rather than by a broad instability in the weighting procedure.</p>
<p>At the 99th-percentile cap the Kish effective sample size rises from 753,325 to 835,618, confirming that the caps do what they are meant to do.</p>
</section>
<section id="c.4-sensitivity-to-correspondence-games" class="level4">
<h4 class="anchored" data-anchor-id="c.4-sensitivity-to-correspondence-games">C.4 Sensitivity to Correspondence games</h4>
<p>Correspondence is structurally unlike the live time controls and contains a far larger share of degenerate games — 21.65% of its games, against a few per cent elsewhere. I therefore repeated the main descriptive calculations after removing all 50,489 Correspondence games, 0.35% of the month.</p>
<p>The results barely move. The overall evaluated share goes from 7.54% to 7.53%, the evaluated-versus-population rating gap from −40.9 to −41.5 points, and the composition component of the Kitagawa decomposition from 24.2% to 24.1%. The within-control comparisons for the remaining five controls are unchanged by construction.</p>
<p>This shows that the headline descriptive conclusions are not driven by the unusual structure of Correspondence games. It is not a general sensitivity analysis over all modelling choices.</p>
</section>
<section id="c.5-participant-history-validation" class="level4">
<h4 class="anchored" data-anchor-id="c.5-participant-history-validation">C.5 Participant-history validation</h4>
<p>Two checks address the construction of the participant-history score.</p>
<p>First, I tested how much the leave-one-out construction matters. On the real data the correctly constructed leave-one-out model has an in-sample AUC of 0.827; if the focal game’s own evaluation status is allowed into its own history score, the AUC rises to 0.853. The increase is artificial, because part of the outcome has entered the predictor. In a synthetic version of the same check the leakage inflates AUC by about 0.16.</p>
<p>Second, I tested whether the pipeline behaves sensibly when the data-generating mechanism is known. In a synthetic scenario where the apparent time-control difference was created entirely by player composition, the Classical-versus-Blitz odds ratio reads 1.66 with no participant-history term, 1.25 with the observed leave-one-out proxy, and 1.05 when that noisy proxy is replaced by the underlying simulated player propensity, binned identically.</p>
<p>The synthetic result has a deliberately limited interpretation. It shows that the implementation can recover a composition-driven pattern when player propensity is measured cleanly, and that measurement noise in the leave-one-out proxy leaves some residual difference. It does not establish that the real Classical–Blitz pattern is caused by player composition, and it does not determine the direction or magnitude of measurement error in the observed data.</p>
</section>
</section>
<section id="d.-exact-results-and-audit-trail" class="level3">
<h3 class="anchored" data-anchor-id="d.-exact-results-and-audit-trail">D. Exact results and audit trail</h3>
<p>The main figures emphasise patterns rather than printing every value. This section gives the exact numbers behind those figures and records where the article’s principal quantitative claims come from.</p>
<section id="d.1-exact-values-behind-the-figures" class="level4">
<h4 class="anchored" data-anchor-id="d.1-exact-values-behind-the-figures">D.1 Exact values behind the figures</h4>
<div id="tbl-c1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-c1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;5&nbsp;— Exact evaluation rates by time control, underlying <a href="#fig-controls" class="quarto-xref">Figure&nbsp;2</a>. The final column compares each control’s analysis rate with the overall 7.54% rate.
</figcaption>
<div aria-describedby="tbl-c1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Time control</th>
<th style="text-align: right;">Games</th>
<th style="text-align: right;">Share analyzed</th>
<th style="text-align: right;">vs overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>UltraBullet (&lt; 30s)</td>
<td style="text-align: right;">304,569</td>
<td style="text-align: right;">4.3%</td>
<td style="text-align: right;">0.57×</td>
</tr>
<tr class="even">
<td>Bullet</td>
<td style="text-align: right;">3,831,325</td>
<td style="text-align: right;">6.1%</td>
<td style="text-align: right;">0.81×</td>
</tr>
<tr class="odd">
<td>Blitz</td>
<td style="text-align: right;">7,009,403</td>
<td style="text-align: right;">6.4%</td>
<td style="text-align: right;">0.84×</td>
</tr>
<tr class="even">
<td>Rapid</td>
<td style="text-align: right;">2,870,138</td>
<td style="text-align: right;">11.2%</td>
<td style="text-align: right;">1.49×</td>
</tr>
<tr class="odd">
<td><strong>Classical (slowest live)</strong></td>
<td style="text-align: right;">240,451</td>
<td style="text-align: right;"><strong>25.0%</strong></td>
<td style="text-align: right;"><strong>3.32×</strong></td>
</tr>
<tr class="even">
<td>Correspondence</td>
<td style="text-align: right;">50,489</td>
<td style="text-align: right;">10.7%</td>
<td style="text-align: right;">1.41×</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-c2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-c2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;6&nbsp;— Within-control change in analysis rate from rating 1200–1400 to 2000–2200, underlying <a href="#fig-interaction" class="quarto-xref">Figure&nbsp;4</a>. Ratios below 1 indicate that higher-rated games are analyzed less often; ratios above 1 indicate that they are analyzed more often.
</figcaption>
<div aria-describedby="tbl-c2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Within…</th>
<th style="text-align: right;">Selection-rate ratio, rating 1200–1400 → 2000–2200</th>
<th>Direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>UltraBullet</td>
<td style="text-align: right;">0.26 [0.22, 0.30]</td>
<td>falling</td>
</tr>
<tr class="even">
<td>Bullet</td>
<td style="text-align: right;">0.30 [0.28, 0.31]</td>
<td>falling</td>
</tr>
<tr class="odd">
<td>Blitz</td>
<td style="text-align: right;">0.86 [0.82, 0.89]</td>
<td>falling</td>
</tr>
<tr class="even">
<td>Rapid</td>
<td style="text-align: right;">2.39 [2.30, 2.49]</td>
<td>rising</td>
</tr>
<tr class="odd">
<td>Classical</td>
<td style="text-align: right;">2.50 [2.33, 2.68]</td>
<td>rising</td>
</tr>
<tr class="even">
<td>Correspondence</td>
<td style="text-align: right;">3.68 [2.83, 4.77]</td>
<td>rising</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-heatmap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/fig3_heatmap.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="FIG.&nbsp;11&nbsp;— Cell-level analysis rates by rating and time control, underlying Figure&nbsp;4. Each cell shows the raw analysis rate; colour indicates how far that rate sits above or below the overall 7.54% rate on a multiplicative log scale. Hatched cells contain fewer than 200 games and are not interpreted. The heatmap makes the level differences visible, while Figure&nbsp;4 shows the within-control trends more clearly."><img src="images/fig3_heatmap.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heatmap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
FIG.&nbsp;11&nbsp;— Cell-level analysis rates by rating and time control, underlying <a href="#fig-interaction" class="quarto-xref">Figure&nbsp;4</a>. Each cell shows the raw analysis rate; colour indicates how far that rate sits above or below the overall 7.54% rate on a multiplicative log scale. Hatched cells contain fewer than 200 games and are not interpreted. The heatmap makes the level differences visible, while <a href="#fig-interaction" class="quarto-xref">Figure&nbsp;4</a> shows the within-control trends more clearly.
</figcaption>
</figure>
</div>
<div id="tbl-c3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-c3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;7&nbsp;— Exact analysis rates by game-length bin, underlying <a href="#fig-length" class="quarto-xref">Figure&nbsp;5</a>. The table also shows how much of the full month falls into each length group.
</figcaption>
<div aria-describedby="tbl-c3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Length (plies)</th>
<th style="text-align: right;">Share of games</th>
<th style="text-align: right;">Share analyzed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0–10</td>
<td style="text-align: right;">1.4%</td>
<td style="text-align: right;"><strong>0.65%</strong></td>
</tr>
<tr class="even">
<td>11–20</td>
<td style="text-align: right;">2.8%</td>
<td style="text-align: right;">3.0%</td>
</tr>
<tr class="odd">
<td>21–40</td>
<td style="text-align: right;">14.2%</td>
<td style="text-align: right;">6.7%</td>
</tr>
<tr class="even">
<td><strong>41–60</strong></td>
<td style="text-align: right;">27.0%</td>
<td style="text-align: right;"><strong>10.4%</strong></td>
</tr>
<tr class="odd">
<td>61–80</td>
<td style="text-align: right;">24.8%</td>
<td style="text-align: right;">8.7%</td>
</tr>
<tr class="even">
<td>81–120</td>
<td style="text-align: right;">23.7%</td>
<td style="text-align: right;">5.3%</td>
</tr>
<tr class="odd">
<td>120+</td>
<td style="text-align: right;">6.1%</td>
<td style="text-align: right;">4.8%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-c4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-c4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;8&nbsp;— Exact analysis rates by participant-history bin, underlying <a href="#fig-history" class="quarto-xref">Figure&nbsp;8</a>. Participant history is the average of the participants’ leave-one-out analysis rates among their other games that month.
</figcaption>
<div aria-describedby="tbl-c4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Participants’ analysis history</th>
<th style="text-align: right;">Games</th>
<th style="text-align: right;">Share analyzed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0-5%</td>
<td style="text-align: right;">6,605,029</td>
<td style="text-align: right;">1.7%</td>
</tr>
<tr class="even">
<td>5-10%</td>
<td style="text-align: right;">4,801,713</td>
<td style="text-align: right;">5.5%</td>
</tr>
<tr class="odd">
<td>10-20%</td>
<td style="text-align: right;">2,084,886</td>
<td style="text-align: right;">16.3%</td>
</tr>
<tr class="even">
<td>20-50%</td>
<td style="text-align: right;">741,585</td>
<td style="text-align: right;">43.1%</td>
</tr>
<tr class="odd">
<td>50-100%</td>
<td style="text-align: right;">52,021</td>
<td style="text-align: right;">79.5%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The five bins above hold 14,285,234 games. The remaining 21,141 are the two groups omitted from <a href="#fig-history" class="quarto-xref">Figure&nbsp;8</a>: 20,706 games whose participants have a leave-one-out rate of exactly zero, and 435 whose participants have no other games at all. Their exact values are in the released output tables.</p>
</section>
<section id="d.2-headline-results-audit-trail" class="level4">
<h4 class="anchored" data-anchor-id="d.2-headline-results-audit-trail">D.2 Headline-results audit trail</h4>
<p>Each row links a reported result to the pipeline output it is drawn from, the script that produces that output, and the interval or verification procedure attached to it. File names are the current pipeline’s names; when the public repository is released they will be mapped to its stable, semantically named outputs.</p>
<div id="tbl-audit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
TAB.&nbsp;9&nbsp;— Source and verification record for the article’s headline results.
</figcaption>
<div aria-describedby="tbl-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Claim</th>
<th>Value</th>
<th>Output table</th>
<th>Python script</th>
<th>Interval method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Share of games with evaluations</td>
<td>7.54% (1,078,379 / 14,306,375)</td>
<td><code>agg_headline.csv</code></td>
<td><code>code_w1/step1_aggregate.py</code></td>
<td>Wilson</td>
</tr>
<tr class="even">
<td>Classical vs UltraBullet selection</td>
<td>25.0% vs 4.3% (5.9×)</td>
<td><code>t3_1_rates.csv</code></td>
<td><code>code_w1/step3_selection.py</code></td>
<td>one-way player bootstrap (B=200)</td>
</tr>
<tr class="odd">
<td>Classical share overstated</td>
<td>5.6% vs 1.7% (3.32×)</td>
<td><code>t3_2_composition.csv</code></td>
<td><code>code_w1/step3_selection.py</code></td>
<td>exact shares</td>
</tr>
<tr class="even">
<td>Rating gap</td>
<td>eval − all: −40.9 (equivalently eval − unevaluated: −44.2 = −40.9/0.9246); SMD −0.157 vs unevaluated</td>
<td><code>t4_5_elo_balance.csv</code></td>
<td><code>code_w1/step4_elo.py</code></td>
<td>one-way player bootstrap: −40.9 [−42.8, −39.0]</td>
</tr>
<tr class="odd">
<td>Kitagawa split</td>
<td>24.2% composition / 75.8% within</td>
<td><code>t4_4_kitagawa.csv</code></td>
<td><code>code_w1/step4_elo.py</code></td>
<td>exact identity; means from lossless counts</td>
</tr>
<tr class="even">
<td>Rating-pool spread</td>
<td>278 points: median 1733 UltraBullet vs 1455 Classical</td>
<td><code>t4_1_elo_by_speed.csv</code></td>
<td><code>code_w1/step4_elo.py</code></td>
<td>descriptive</td>
</tr>
<tr class="odd">
<td>Six within-control ratios</td>
<td>0.26 → 3.68, reversal Blitz↔︎Rapid</td>
<td><code>t4_3_crossover.csv</code></td>
<td><code>code_w1/step4_elo.py</code></td>
<td>one-way player bootstrap on log ratio (B=200)</td>
</tr>
<tr class="even">
<td>U-shape of marginal rating curve</td>
<td>10.9% → 6.2% (1800–2000) → 11.3%</td>
<td><code>t3_4_rate_by_elo.csv</code></td>
<td><code>code_w1/step3_selection.py</code></td>
<td>one-way player bootstrap (B=200)</td>
</tr>
<tr class="odd">
<td>Length means / distance</td>
<td>−3.5 plies / Wasserstein 6.84</td>
<td><code>t5_2_ply_balance.csv</code></td>
<td><code>code_w1/step5_length.py</code></td>
<td>exact from lossless counts</td>
</tr>
<tr class="even">
<td>16-fold hump, peak 41–60</td>
<td>0.65% → 10.4%</td>
<td><code>t5_1_ply_bins.csv</code></td>
<td><code>code_w1/step5_length.py</code></td>
<td>one-way player bootstrap (B=200)</td>
</tr>
<tr class="odd">
<td>Length tail shares</td>
<td>≤10 plies: 0.124% of evaluated vs 1.55% of unevaluated (12.5×); &gt;120 plies: 3.86% vs 6.24%</td>
<td><code>t5_1_ply_bins.csv</code></td>
<td><code>code_w1/step5_length.py</code></td>
<td>exact shares</td>
</tr>
<tr class="even">
<td>Selection-model AUC (in-sample)</td>
<td>0.664</td>
<td><code>t7_2_model_fit.csv</code></td>
<td><code>code_w4/step9_model.py</code></td>
<td>one-way player bootstrap, full-pipeline refit (B=200): [0.662, 0.665]</td>
</tr>
<tr class="odd">
<td>In-model closure after IPW</td>
<td>Classical share 99.2%; mean rating 98.6%; length 72.4%</td>
<td><code>t7_4_threepoint.csv</code></td>
<td><code>code_w4/step10_ipw.py</code></td>
<td>gap CIs from same bootstrap</td>
</tr>
<tr class="even">
<td>Holdout-variable closure after IPW</td>
<td>29–47% per quantity (fixable median 43%)</td>
<td><code>t7_4_threepoint.csv</code></td>
<td><code>code_w4/step10_ipw.py</code></td>
<td>same</td>
</tr>
<tr class="odd">
<td>Games-per-player after IPW</td>
<td>368 → 425 (benchmark 508)</td>
<td><code>t7_4_threepoint.csv</code></td>
<td><code>code_w4/step10_ipw.py</code></td>
<td>weighted point CI [418, 433]</td>
</tr>
<tr class="even">
<td>Zero and near-zero overlap</td>
<td>Unterminated 0/7,592 evaluated; Abandoned 0.0039% raw vs 0.412% benchmark</td>
<td><code>t3_1_rates.csv</code>, <code>t7_4_threepoint.csv</code></td>
<td><code>code_w1/step3_selection.py</code>, <code>code_w4/step10_ipw.py</code></td>
<td>Wilson upper 0.05%; flagged absent-in-selected</td>
</tr>
<tr class="odd">
<td>Harm case</td>
<td>Rules infraction: benchmark 0.0069% → weighted 0.0127%</td>
<td><code>t7_4_threepoint.csv</code></td>
<td><code>code_w4/step10_ipw.py</code></td>
<td>CI [0.0092%, 0.0162%] excludes truth</td>
</tr>
<tr class="even">
<td>Analysis-history gradient</td>
<td>1.7% → 79.5% analyzed (47-fold) across history bins</td>
<td><code>t8_4_habit_bins.csv</code></td>
<td><code>code_w5/step11_player.py</code></td>
<td>descriptive counts</td>
</tr>
<tr class="odd">
<td>AUC ladder (in-sample)</td>
<td>0.664 → 0.827 adding one participant-history variable</td>
<td><code>t8_3_auc_ladder.csv</code></td>
<td><code>code_w5/step11_player.py</code></td>
<td>one-way player bootstrap: [0.826, 0.828]</td>
</tr>
<tr class="even">
<td>Classical OR collapse</td>
<td>4.69 [4.51, 4.88] → 0.99 [0.96, 1.02]</td>
<td><code>t8_2_or_collapse.csv</code></td>
<td><code>code_w5/step11_player.py</code></td>
<td>same bootstrap, both models refit per replicate</td>
</tr>
<tr class="odd">
<td>Hierarchy ends flip</td>
<td>UltraBullet 0.94 → 1.50 [1.41, 1.60]; Correspondence 1.26 → 0.59 [0.55, 0.63]</td>
<td><code>t8_2_or_collapse.csv</code></td>
<td><code>code_w5/step11_player.py</code></td>
<td>same</td>
</tr>
<tr class="even">
<td>Weight truncation sensitivity</td>
<td>Length closure 72.4% → 89.0%; harm case −234% → −126%</td>
<td><code>t9_3_truncation.csv</code></td>
<td><code>code_w6/step13_truncation.py</code></td>
<td>point-value only</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The cell table <code>t7_3_cells.csv</code> lists the fitted cell probabilities, so any individual weight can be recomputed by hand as <span class="math inline">\(1/\hat{\pi}\)</span>.</p>
</section>
<section id="verification-notes" class="level4">
<h4 class="anchored" data-anchor-id="verification-notes">Verification notes</h4>
<p>The pipeline carries several implementation checks that are separate from the statistical robustness work above. Aggregate game counts are asserted against registered reference totals, and the run aborts on a mismatch. The PGN parser was validated against <code>python-chess</code> on a 1,000-game sample. The §2–§4 descriptive rates were cross-checked against two independent earlier implementations, agreeing on all 41 compared quantities. The Kitagawa components are required to sum to the observed rating gap, and the one-dimensional Wasserstein distance is checked against its equivalent empirical-CDF area representation, both asserted at runtime.</p>
<p>These checks verify that the code computes what it claims to compute. The checks that address modelling assumptions and sensitivity are in Appendix C.</p>
</section>
</section>
<section id="appendix-e" class="level3">
<h3 class="anchored" data-anchor-id="appendix-e">E. Data, code, and AI assistance</h3>
<section id="e.1-data-availability" class="level4">
<h4 class="anchored" data-anchor-id="e.1-data-availability">E.1 Data availability</h4>
<p>The analysis uses the November 2017 Lichess standard-rated-games database, <code>lichess_db_standard_rated_2017-11.pgn</code>, published by Lichess at <a href="https://database.lichess.org/">database.lichess.org</a> under the Creative Commons CC0 public-domain dedication.</p>
<p>The raw PGN is not redistributed here; the pipeline reads the original Lichess file directly. One pass over the dump compresses losslessly into contingency tables of about 4 MB, and every descriptive result in §2–§4 is recomputed from those tables rather than from a re-parse.</p>
</section>
<section id="e.2-code-and-reproducibility" class="level4">
<h4 class="anchored" data-anchor-id="e.2-code-and-reproducibility">E.2 Code and reproducibility</h4>
<p>The complete analysis code and derived outputs are being prepared for public release and will be linked from this section; they are available on request in the meantime. The repository will contain the code that parses the PGN, builds the descriptive summaries, fits the selection models, performs the weighting and robustness checks, constructs the participant-history analysis, and generates every table and figure in this article.</p>
<p>It will be organised as a reproducible pipeline rather than as the original research workspace: the README documents the required environment, where to obtain the data, the execution order, and the mapping from scripts to final outputs. Intermediate development files and superseded analyses are not part of the release. Because the Lichess database is large, the raw PGN is not included; the compact derived tables needed to check the reported results are included where practical.</p>
<p>Until the repository is public, Appendices A–D are written to stand on their own. They give the population definition, the model specification, the reference cell, the bin edges, the bootstrap scheme, and the diagnostic values needed to reimplement or check any number in the article.</p>
</section>
<section id="e.3-ai-assistance" class="level4">
<h4 class="anchored" data-anchor-id="e.3-ai-assistance">E.3 AI assistance</h4>
<p>Generative AI tools assisted with code development, figure-generation code, and final-language editing. The research question, statistical design, choice of methods, validation strategy, interpretation of results, and final analytical decisions were made by the author.</p>
<p>All reported numerical results were checked against the analysis pipeline rather than accepted from generated text.</p>


</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Here, the population is every game retained from <code>lichess_db_standard_rated_2017-11.pgn</code>. The file already contains only standard rated games; variants are published separately and casual games are not included. I exclude only records with non-numeric rating fields, leaving 14,306,375 games.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The PGN does not record who requested the analysis. It could be either player or someone else viewing the game later, so an evaluation can be treated as a game-level selection indicator, but not as an observed decision by a specific participant.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Lichess assigns time-control categories from estimated game duration, calculated from the initial clock and increment. Classical begins at roughly 25 minutes per player, while UltraBullet is under about 30 seconds.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>A game’s rating is the mean of the two players’ pre-game ratings.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The 41-point gap compares evaluated games with the full month. Comparing evaluated games with the unevaluated remainder instead gives a 44-point gap. Standardized by the pooled rating spread, the evaluated-versus-unevaluated difference is −0.16 standard deviations.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>A decomposition that splits a difference in group averages into a composition component and a within-group component. I use the symmetric (midpoint-weighted) version here; the formula and alternative conventions are described in the appendix.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>A 95% interval obtained by resampling players rather than individual games. It describes how stable the result is to changes in player composition while preserving the clustering of games within players.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>A reweighting method that gives more influence to observations that were less likely to be selected. Here, an evaluated game with estimated analysis probability <span class="math inline">\(p\)</span> receives weight <span class="math inline">\(1/p\)</span>, so rarely evaluated kinds of game represent more of their unevaluated counterparts.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>A statistical model for yes-or-no outcomes. Here it combines several game characteristics to estimate the probability that a game carries an evaluation.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>The predictors enter as categories rather than continuous values. This preserves the rating reversal and the length hump without imposing a single linear shape, but treats games within the same bin as equivalent. Full model details and reference categories are in the appendix.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Recorded variables chosen in advance and deliberately excluded from the weighting model — not held-out games. If weighting also reduces their discrepancies, that is evidence the adjustment generalizes beyond simply balancing the variables it was built from.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>The PGN does not record who requested the analysis. It could be either player or someone else viewing the game later, so an evaluation can be treated as a game-level selection indicator, but not as an observed decision by a specific participant.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>For each game, participant history is the average of the participants’ leave-one-out analysis rates among their other games that month. It is a retrospective within-month measure, not a record of behaviour strictly before the focal game.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>A measure of how well a model ranks the two groups apart. Here, AUC is the probability that a randomly chosen evaluated game receives a higher predicted analysis probability than a randomly chosen unevaluated game. An AUC of 0.5 corresponds to chance ranking; 1.0 to perfect ranking.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>An odds ratio compares the odds of an outcome between two groups. A ratio of 1 means equal odds; above 1 means the first group has higher odds, below 1 means lower. Here the comparison is against Blitz at the model’s reference profile.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>In a synthetic check where the apparent time-control pattern was caused entirely by player composition, the noisy leave-one-out history score removed only part of that pattern, while the true simulated player propensity removed almost all of it. This confirms that measurement noise can weaken the apparent collapse in that controlled scenario; it does not determine the direction or size of bias in the real data. Full results are in the appendix.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>A proxy variable is an observed measurement used as an imperfect stand-in for something that cannot be observed directly. Here, participant history could partly stand in for underlying differences between players.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>Overadjustment occurs when controlling for a variable removes part of the relationship you are trying to study, because that variable already lies on, or carries part of, the relevant pathway.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>I did not add participant history to the weighting model. Doing so would require rerunning the weighting and holdout-validation pipeline, and the higher AUC alone does not show that adding history would produce better weights.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>The nine studies were chosen purposively to inspect their data pipelines, not sampled to represent the literature. Any count reported here applies only to those studies and should not be read as an estimate of how common a practice is overall.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script>
/*
 * C2 · Atelier — two DOM touches Quarto's templates do not expose:
 *   1. the signature sparkline beside the wordmark
 *   2. wrapping "FIG. N —" so only the label carries terracotta
 * Everything else is CSS in custom.scss.
 */
(function () {
  /* The U-curve is drawn from this site's own data: evaluation rate across the
     nine rating bins of §4. Path copied verbatim from the approved specimen. */
  var SPARK =
    '<svg class="spark" viewBox="0 0 240 34" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">' +
    '<path d="M 3.0 5.2 L 32.2 10.1 L 61.5 16.2 L 90.8 21.1 L 120.0 27.7 L 149.2 31.0 L 178.5 30.2 L 207.8 29.4 L 237.0 3.0" ' +
    'stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" stroke-linecap="round"/>' +
    '<circle cx="3.0" cy="5.2" r="2.2" fill="currentColor"/>' +
    '<circle cx="149.2" cy="31.0" r="2.2" fill="currentColor"/>' +
    '<circle cx="237.0" cy="3.0" r="2.2" fill="currentColor"/></svg>';

  function addSparkline() {
    var brand = document.querySelector(".navbar-brand");
    if (!brand || brand.querySelector(".spark")) return;
    brand.insertAdjacentHTML("beforeend", SPARK);
  }

  /* Quarto emits "FIG.<nbsp>3 — caption" as one text node. Split off the label
     so the number can carry terracotta without touching the article source.
     Tables get the same treatment (§5: the numbering habit is a signature). */
  function markFigureNumbers() {
    var caps = document.querySelectorAll(
      "figcaption.quarto-float-caption, figure > figcaption, table > caption");
    Array.prototype.forEach.call(caps, function (cap) {
      if (cap.querySelector(".fignum")) return;
      var node = null;
      for (var i = 0; i < cap.childNodes.length; i++) {
        if (cap.childNodes[i].nodeType === 3 && cap.childNodes[i].nodeValue.trim()) {
          node = cap.childNodes[i];
          break;
        }
      }
      if (!node) return;
      var m = node.nodeValue.match(/^(\s*)((?:FIG|TAB)\.[\s ]*\d+)(\s*[—:-]?\s*)/i);
      if (!m) return;
      var span = document.createElement("span");
      span.className = "fignum";
      span.textContent = m[2].replace(/[\s ]+/g, " ");
      node.nodeValue = node.nodeValue.slice(m[0].length);
      cap.insertBefore(document.createTextNode(" — "), node);
      cap.insertBefore(span, cap.firstChild);
    });
  }

  /* Ten glossary notes are written as <strong>term</strong><sup-ref>. Only the
     superscript is hoverable by default, which is a small target for a word
     the reader is actually stuck on. Extend each note's trigger to cover the
     term itself. Quarto builds its tippy instances after this script runs, so
     this waits for load rather than DOMContentLoaded. */
  /* The term must be immediately before the reference, with nothing but
     whitespace between. previousElementSibling is not enough: it skips over
     text nodes, so a run-in bold heading earlier in the same paragraph would
     be claimed by a note at the end of the sentence. The article has 42 bold
     spans and only 11 are glossary terms. */
  function adjacentStrong(ref) {
    var n = ref.previousSibling;
    while (n && n.nodeType === 3 && n.nodeValue.trim() === "") {
      n = n.previousSibling;
    }
    return (n && n.nodeType === 1 && n.tagName === "STRONG") ? n : null;
  }

  function linkTermsToNotes() {
    var refs = document.querySelectorAll('a[role="doc-noteref"]');
    Array.prototype.forEach.call(refs, function (ref) {
      var term = adjacentStrong(ref);
      if (!term) return;
      term.classList.add("term-hover");
      if (!ref._tippy || typeof ref._tippy.setProps !== "function") return;
      try {
        ref._tippy.setProps({ triggerTarget: [term, ref] });
      } catch (e) {
        /* older tippy: the superscript stays the trigger, underline still hints */
      }
    });
  }

  function init() { addSparkline(); markFigureNumbers(); }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
  if (document.readyState === "complete") {
    linkTermsToNotes();
  } else {
    window.addEventListener("load", linkTermsToNotes);
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/yifanmillerliao\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"right","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>